/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AccountStats,
} from '../models/index';
import {
    AccountStatsFromJSON,
    AccountStatsToJSON,
} from '../models/index';

/**
 * 
 */
export class AccountStatsApi extends runtime.BaseAPI {

    /**
     * Get the Account statistics, such the number of products, product groups and urls in the KG.
     * Get my Account statistics
     */
    async getMyStatsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountStats>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }

        const response = await this.request({
            path: `/accounts/me/stats`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountStatsFromJSON(jsonValue));
    }

    /**
     * Get the Account statistics, such the number of products, product groups and urls in the KG.
     * Get my Account statistics
     */
    async getMyStats(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountStats> {
        const response = await this.getMyStatsRaw(initOverrides);
        return await response.value();
    }

}
