/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ContentGenerationStats,
} from '../models';
import {
    ContentGenerationStatsFromJSON,
    ContentGenerationStatsToJSON,
} from '../models';

export interface Get4Request {
    contentGenerationId: number;
}

/**
 * 
 */
export class ContentGenerationStatsApi extends runtime.BaseAPI {

    /**
     * Get
     */
    async get4Raw(requestParameters: Get4Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ContentGenerationStats>> {
        if (requestParameters.contentGenerationId === null || requestParameters.contentGenerationId === undefined) {
            throw new runtime.RequiredError('contentGenerationId','Required parameter requestParameters.contentGenerationId was null or undefined when calling get4.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKey authentication
        }

        const response = await this.request({
            path: `/content-generations/{contentGenerationId}/stats`.replace(`{${"contentGenerationId"}}`, encodeURIComponent(String(requestParameters.contentGenerationId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ContentGenerationStatsFromJSON(jsonValue));
    }

    /**
     * Get
     */
    async get4(requestParameters: Get4Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ContentGenerationStats> {
        const response = await this.get4Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
