/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PagePreset,
} from '../models';
import {
    PagePresetFromJSON,
    PagePresetToJSON,
} from '../models';

export interface ListPresetsRequest {
    cursor?: string;
    limit?: number;
}

/**
 * 
 */
export class ContentGenerationPresetsApi extends runtime.BaseAPI {

    /**
     * List
     */
    async listPresetsRaw(requestParameters: ListPresetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PagePreset>> {
        const queryParameters: any = {};

        if (requestParameters.cursor !== undefined) {
            queryParameters['cursor'] = requestParameters.cursor;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKey authentication
        }

        const response = await this.request({
            path: `/graphql-query-presets`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PagePresetFromJSON(jsonValue));
    }

    /**
     * List
     */
    async listPresets(requestParameters: ListPresetsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PagePreset> {
        const response = await this.listPresetsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
