/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AnalysesResponse,
  EntityGapRequest,
} from '../models';
import {
    AnalysesResponseFromJSON,
    AnalysesResponseToJSON,
    EntityGapRequestFromJSON,
    EntityGapRequestToJSON,
} from '../models';

export interface CreateEntityGapRequest {
    entityGapRequest: EntityGapRequest;
}

/**
 * 
 */
export class EntityGapsApi extends runtime.BaseAPI {

    /**
     * Create an Entity Gaps analysis.
     * Create
     */
    async createEntityGapRaw(requestParameters: CreateEntityGapRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AnalysesResponse>> {
        if (requestParameters.entityGapRequest === null || requestParameters.entityGapRequest === undefined) {
            throw new runtime.RequiredError('entityGapRequest','Required parameter requestParameters.entityGapRequest was null or undefined when calling createEntityGap.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKey authentication
        }

        const response = await this.request({
            path: `/entity-gaps`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EntityGapRequestToJSON(requestParameters.entityGapRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AnalysesResponseFromJSON(jsonValue));
    }

    /**
     * Create an Entity Gaps analysis.
     * Create
     */
    async createEntityGap(requestParameters: CreateEntityGapRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AnalysesResponse> {
        const response = await this.createEntityGapRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
