/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  NodeRequest,
} from '../models/index';
import {
    NodeRequestFromJSON,
    NodeRequestToJSON,
} from '../models/index';

export interface UpdateNodesCollectionRequest {
    nodeRequest: Array<NodeRequest>;
}

/**
 * 
 */
export class VectorSearchNodesApi extends runtime.BaseAPI {

    /**
     * Update
     */
    async updateNodesCollectionRaw(requestParameters: UpdateNodesCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['nodeRequest'] == null) {
            throw new runtime.RequiredError(
                'nodeRequest',
                'Required parameter "nodeRequest" was null or undefined when calling updateNodesCollection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }

        const response = await this.request({
            path: `/vector-search/nodes-collection`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['nodeRequest']!.map(NodeRequestToJSON),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update
     */
    async updateNodesCollection(requestParameters: UpdateNodesCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateNodesCollectionRaw(requestParameters, initOverrides);
    }

}
