/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An Add-On configuration
 * @export
 * @interface AddOnConfiguration
 */
export interface AddOnConfiguration {
    /**
     * Whether this Add-on can do content expansion
     * @type {boolean}
     * @memberof AddOnConfiguration
     */
    readonly canDoContentExpansion?: boolean;
    /**
     * Whether this Add-on can import to WordPress.
     * @type {boolean}
     * @memberof AddOnConfiguration
     */
    readonly canImportToWordpress?: boolean;
    /**
     * A key
     * @type {string}
     * @memberof AddOnConfiguration
     */
    readonly key?: string;
    /**
     * The wp-admin endpoint for a website using the key.
     * @type {string}
     * @memberof AddOnConfiguration
     */
    readonly wpAdmin?: string;
    /**
     * The wp-json endpoint for a website using the key.
     * @type {string}
     * @memberof AddOnConfiguration
     */
    readonly wpJson?: string;
}

/**
 * Check if a given object implements the AddOnConfiguration interface.
 */
export function instanceOfAddOnConfiguration(value: object): value is AddOnConfiguration {
    return true;
}

export function AddOnConfigurationFromJSON(json: any): AddOnConfiguration {
    return AddOnConfigurationFromJSONTyped(json, false);
}

export function AddOnConfigurationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddOnConfiguration {
    if (json == null) {
        return json;
    }
    return {
        
        'canDoContentExpansion': json['can_do_content_expansion'] == null ? undefined : json['can_do_content_expansion'],
        'canImportToWordpress': json['can_import_to_wordpress'] == null ? undefined : json['can_import_to_wordpress'],
        'key': json['key'] == null ? undefined : json['key'],
        'wpAdmin': json['wp_admin'] == null ? undefined : json['wp_admin'],
        'wpJson': json['wp_json'] == null ? undefined : json['wp_json'],
    };
}

export function AddOnConfigurationToJSON(json: any): AddOnConfiguration {
    return AddOnConfigurationToJSONTyped(json, false);
}

export function AddOnConfigurationToJSONTyped(value?: Omit<AddOnConfiguration, 'can_do_content_expansion'|'can_import_to_wordpress'|'key'|'wp_admin'|'wp_json'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

