/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnalysesResponseItem
 */
export interface AnalysesResponseItem {
    /**
     * The text matching the entity.
     * @type {string}
     * @memberof AnalysesResponseItem
     */
    text?: string;
    /**
     * The confidence score this is the right entity.
     * @type {number}
     * @memberof AnalysesResponseItem
     */
    confidence?: number;
    /**
     * The number of occurrences.
     * @type {number}
     * @memberof AnalysesResponseItem
     */
    occurrences?: number;
    /**
     * The position of the entity in SERP. `null` if not applicable.
     * @type {number}
     * @memberof AnalysesResponseItem
     */
    serpPosition?: number;
    /**
     * The entity id (URI).
     * @type {string}
     * @memberof AnalysesResponseItem
     */
    entityId?: string;
    /**
     * The entity label.
     * @type {string}
     * @memberof AnalysesResponseItem
     */
    entityLabel?: string;
    /**
     * The entity type.
     * @type {string}
     * @memberof AnalysesResponseItem
     */
    entityType?: string;
    /**
     * The entity description.
     * @type {string}
     * @memberof AnalysesResponseItem
     */
    entityDescription?: string;
}

/**
 * Check if a given object implements the AnalysesResponseItem interface.
 */
export function instanceOfAnalysesResponseItem(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AnalysesResponseItemFromJSON(json: any): AnalysesResponseItem {
    return AnalysesResponseItemFromJSONTyped(json, false);
}

export function AnalysesResponseItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalysesResponseItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'text': !exists(json, 'text') ? undefined : json['text'],
        'confidence': !exists(json, 'confidence') ? undefined : json['confidence'],
        'occurrences': !exists(json, 'occurrences') ? undefined : json['occurrences'],
        'serpPosition': !exists(json, 'serp_position') ? undefined : json['serp_position'],
        'entityId': !exists(json, 'entity_id') ? undefined : json['entity_id'],
        'entityLabel': !exists(json, 'entity_label') ? undefined : json['entity_label'],
        'entityType': !exists(json, 'entity_type') ? undefined : json['entity_type'],
        'entityDescription': !exists(json, 'entity_description') ? undefined : json['entity_description'],
    };
}

export function AnalysesResponseItemToJSON(value?: AnalysesResponseItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'text': value.text,
        'confidence': value.confidence,
        'occurrences': value.occurrences,
        'serp_position': value.serpPosition,
        'entity_id': value.entityId,
        'entity_label': value.entityLabel,
        'entity_type': value.entityType,
        'entity_description': value.entityDescription,
    };
}

