/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnalysesResponseItem
 */
export interface AnalysesResponseItem {
    /**
     * The text matching the entity.
     * @type {string}
     * @memberof AnalysesResponseItem
     */
    text?: string;
    /**
     * The confidence score this is the right entity.
     * @type {number}
     * @memberof AnalysesResponseItem
     */
    confidence?: number;
    /**
     * The number of occurrences.
     * @type {number}
     * @memberof AnalysesResponseItem
     */
    occurrences?: number;
    /**
     * The position of the entity in SERP. `null` if not applicable.
     * @type {number}
     * @memberof AnalysesResponseItem
     */
    serpPosition?: number;
    /**
     * The entity id (URI).
     * @type {string}
     * @memberof AnalysesResponseItem
     */
    entityId?: string;
    /**
     * The entity label.
     * @type {string}
     * @memberof AnalysesResponseItem
     */
    entityLabel?: string;
    /**
     * The entity type.
     * @type {string}
     * @memberof AnalysesResponseItem
     */
    entityType?: string;
    /**
     * The entity description.
     * @type {string}
     * @memberof AnalysesResponseItem
     */
    entityDescription?: string;
}

/**
 * Check if a given object implements the AnalysesResponseItem interface.
 */
export function instanceOfAnalysesResponseItem(value: object): value is AnalysesResponseItem {
    return true;
}

export function AnalysesResponseItemFromJSON(json: any): AnalysesResponseItem {
    return AnalysesResponseItemFromJSONTyped(json, false);
}

export function AnalysesResponseItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalysesResponseItem {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'] == null ? undefined : json['text'],
        'confidence': json['confidence'] == null ? undefined : json['confidence'],
        'occurrences': json['occurrences'] == null ? undefined : json['occurrences'],
        'serpPosition': json['serp_position'] == null ? undefined : json['serp_position'],
        'entityId': json['entity_id'] == null ? undefined : json['entity_id'],
        'entityLabel': json['entity_label'] == null ? undefined : json['entity_label'],
        'entityType': json['entity_type'] == null ? undefined : json['entity_type'],
        'entityDescription': json['entity_description'] == null ? undefined : json['entity_description'],
    };
}

export function AnalysesResponseItemToJSON(json: any): AnalysesResponseItem {
    return AnalysesResponseItemToJSONTyped(json, false);
}

export function AnalysesResponseItemToJSONTyped(value?: AnalysesResponseItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'confidence': value['confidence'],
        'occurrences': value['occurrences'],
        'serp_position': value['serpPosition'],
        'entity_id': value['entityId'],
        'entity_label': value['entityLabel'],
        'entity_type': value['entityType'],
        'entity_description': value['entityDescription'],
    };
}

