/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * An Analytics Import request.
 * @export
 * @interface AnalyticsImportRequest
 */
export interface AnalyticsImportRequest {
    /**
     * An array of URLs.
     * @type {Set<string>}
     * @memberof AnalyticsImportRequest
     */
    urls?: Set<string>;
}

/**
 * Check if a given object implements the AnalyticsImportRequest interface.
 */
export function instanceOfAnalyticsImportRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AnalyticsImportRequestFromJSON(json: any): AnalyticsImportRequest {
    return AnalyticsImportRequestFromJSONTyped(json, false);
}

export function AnalyticsImportRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsImportRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'urls': !exists(json, 'urls') ? undefined : json['urls'],
    };
}

export function AnalyticsImportRequestToJSON(value?: AnalyticsImportRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'urls': value.urls === undefined ? undefined : Array.from(value.urls as Set<any>),
    };
}

