/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AskResponse
 */
export interface AskResponse {
    /**
     * 
     * @type {string}
     * @memberof AskResponse
     */
    response: string;
}

/**
 * Check if a given object implements the AskResponse interface.
 */
export function instanceOfAskResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "response" in value;

    return isInstance;
}

export function AskResponseFromJSON(json: any): AskResponse {
    return AskResponseFromJSONTyped(json, false);
}

export function AskResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AskResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': json['response'],
    };
}

export function AskResponseToJSON(value?: AskResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': value.response,
    };
}

