/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The author request.
 * @export
 * @interface AuthorRequest
 */
export interface AuthorRequest {
    /**
     * The name of the author, e.g. `John Smith`.
     * @type {string}
     * @memberof AuthorRequest
     */
    name: string;
}

/**
 * Check if a given object implements the AuthorRequest interface.
 */
export function instanceOfAuthorRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function AuthorRequestFromJSON(json: any): AuthorRequest {
    return AuthorRequestFromJSONTyped(json, false);
}

export function AuthorRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthorRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function AuthorRequestToJSON(value?: AuthorRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

