/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A request part of a batch.
 * @export
 * @interface BatchRequest
 */
export interface BatchRequest {
    /**
     * The entity URI.
     * @type {string}
     * @memberof BatchRequest
     */
    uri: string;
    /**
     * 
     * @type {string}
     * @memberof BatchRequest
     */
    model: string;
    /**
     * Whether the entity should be hidden from Linked Data and GraphQL.
     * @type {boolean}
     * @memberof BatchRequest
     */
    _private?: boolean;
}

/**
 * Check if a given object implements the BatchRequest interface.
 */
export function instanceOfBatchRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "uri" in value;
    isInstance = isInstance && "model" in value;

    return isInstance;
}

export function BatchRequestFromJSON(json: any): BatchRequest {
    return BatchRequestFromJSONTyped(json, false);
}

export function BatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uri': json['uri'],
        'model': json['model'],
        '_private': !exists(json, 'private') ? undefined : json['private'],
    };
}

export function BatchRequestToJSON(value?: BatchRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uri': value.uri,
        'model': value.model,
        'private': value._private,
    };
}

