/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClassificationResponse
 */
export interface ClassificationResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof ClassificationResponse
     */
    labels?: Array<string>;
    /**
     * 
     * @type {Array<number>}
     * @memberof ClassificationResponse
     */
    scores?: Array<number>;
}

/**
 * Check if a given object implements the ClassificationResponse interface.
 */
export function instanceOfClassificationResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ClassificationResponseFromJSON(json: any): ClassificationResponse {
    return ClassificationResponseFromJSONTyped(json, false);
}

export function ClassificationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassificationResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'labels': !exists(json, 'labels') ? undefined : json['labels'],
        'scores': !exists(json, 'scores') ? undefined : json['scores'],
    };
}

export function ClassificationResponseToJSON(value?: ClassificationResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'labels': value.labels,
        'scores': value.scores,
    };
}

