/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClassificationRequest
 */
export interface ClassificationRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof ClassificationRequest
     */
    classes?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ClassificationRequest
     */
    text?: string;
}

/**
 * Check if a given object implements the ClassificationRequest interface.
 */
export function instanceOfClassificationRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ClassificationRequestFromJSON(json: any): ClassificationRequest {
    return ClassificationRequestFromJSONTyped(json, false);
}

export function ClassificationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassificationRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'classes': !exists(json, 'classes') ? undefined : json['classes'],
        'text': !exists(json, 'text') ? undefined : json['text'],
    };
}

export function ClassificationRequestToJSON(value?: ClassificationRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'classes': value.classes,
        'text': value.text,
    };
}

