/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClassificationResponse
 */
export interface ClassificationResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof ClassificationResponse
     */
    labels?: Array<string>;
    /**
     * 
     * @type {Array<number>}
     * @memberof ClassificationResponse
     */
    scores?: Array<number>;
}

/**
 * Check if a given object implements the ClassificationResponse interface.
 */
export function instanceOfClassificationResponse(value: object): value is ClassificationResponse {
    return true;
}

export function ClassificationResponseFromJSON(json: any): ClassificationResponse {
    return ClassificationResponseFromJSONTyped(json, false);
}

export function ClassificationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassificationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'labels': json['labels'] == null ? undefined : json['labels'],
        'scores': json['scores'] == null ? undefined : json['scores'],
    };
}

export function ClassificationResponseToJSON(json: any): ClassificationResponse {
    return ClassificationResponseToJSONTyped(json, false);
}

export function ClassificationResponseToJSONTyped(value?: ClassificationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'labels': value['labels'],
        'scores': value['scores'],
    };
}

