/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EntityPatchRequest
 */
export interface EntityPatchRequest {
    /**
     * The patch operation, example `add`.
     * @type {string}
     * @memberof EntityPatchRequest
     */
    op?: EntityPatchRequestOpEnum;
    /**
     * The property to apply the operation, JSONPath formatted (leading slash) on, e.g. `/https://schema.org/image (note the leading slash).
     * @type {string}
     * @memberof EntityPatchRequest
     */
    path?: string;
    /**
     * 
     * @type {string}
     * @memberof EntityPatchRequest
     */
    value?: string;
}


/**
 * @export
 */
export const EntityPatchRequestOpEnum = {
    Add: 'add',
    Remove: 'remove',
    Replace: 'replace',
    Move: 'move',
    Copy: 'copy',
    Test: 'test',
    Add: 'add',
    Remove: 'remove',
    Replace: 'replace'
} as const;
export type EntityPatchRequestOpEnum = typeof EntityPatchRequestOpEnum[keyof typeof EntityPatchRequestOpEnum];


/**
 * Check if a given object implements the EntityPatchRequest interface.
 */
export function instanceOfEntityPatchRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EntityPatchRequestFromJSON(json: any): EntityPatchRequest {
    return EntityPatchRequestFromJSONTyped(json, false);
}

export function EntityPatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityPatchRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'op': !exists(json, 'op') ? undefined : json['op'],
        'path': !exists(json, 'path') ? undefined : json['path'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function EntityPatchRequestToJSON(value?: EntityPatchRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'op': value.op,
        'path': value.path,
        'value': value.value,
    };
}

