/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Properties1 } from './Properties1';
import {
    Properties1FromJSON,
    Properties1FromJSONTyped,
    Properties1ToJSON,
} from './Properties1';

/**
 * The list of entities matching the query.
 * @export
 * @interface Entity1
 */
export interface Entity1 {
    /**
     * The referenced entity URI
     * @type {string}
     * @memberof Entity1
     */
    reference?: string;
    /**
     * 
     * @type {Properties1}
     * @memberof Entity1
     */
    properties?: Properties1;
}

/**
 * Check if a given object implements the Entity1 interface.
 */
export function instanceOfEntity1(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function Entity1FromJSON(json: any): Entity1 {
    return Entity1FromJSONTyped(json, false);
}

export function Entity1FromJSONTyped(json: any, ignoreDiscriminator: boolean): Entity1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'reference': !exists(json, 'reference') ? undefined : json['reference'],
        'properties': !exists(json, 'properties') ? undefined : Properties1FromJSON(json['properties']),
    };
}

export function Entity1ToJSON(value?: Entity1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'reference': value.reference,
        'properties': Properties1ToJSON(value.properties),
    };
}

