/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Event
 */
export interface Event {
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    source?: string;
    /**
     * 
     * @type {object}
     * @memberof Event
     */
    args?: object;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    url?: string;
    /**
     * 
     * @type {Date}
     * @memberof Event
     */
    recordedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof Event
     */
    accountId?: number;
}

/**
 * Check if a given object implements the Event interface.
 */
export function instanceOfEvent(value: object): value is Event {
    return true;
}

export function EventFromJSON(json: any): Event {
    return EventFromJSONTyped(json, false);
}

export function EventFromJSONTyped(json: any, ignoreDiscriminator: boolean): Event {
    if (json == null) {
        return json;
    }
    return {
        
        'source': json['source'] == null ? undefined : json['source'],
        'args': json['args'] == null ? undefined : json['args'],
        'url': json['url'] == null ? undefined : json['url'],
        'recordedAt': json['recorded_at'] == null ? undefined : (new Date(json['recorded_at'])),
        'accountId': json['account_id'] == null ? undefined : json['account_id'],
    };
}

export function EventToJSON(json: any): Event {
    return EventToJSONTyped(json, false);
}

export function EventToJSONTyped(value?: Event | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'source': value['source'],
        'args': value['args'],
        'url': value['url'],
        'recorded_at': value['recordedAt'] == null ? undefined : ((value['recordedAt']).toISOString()),
        'account_id': value['accountId'],
    };
}

