/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Event
 */
export interface Event {
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    source?: string;
    /**
     * 
     * @type {object}
     * @memberof Event
     */
    args?: object;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    url?: string;
    /**
     * 
     * @type {Date}
     * @memberof Event
     */
    recordedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof Event
     */
    accountId?: number;
}

/**
 * Check if a given object implements the Event interface.
 */
export function instanceOfEvent(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EventFromJSON(json: any): Event {
    return EventFromJSONTyped(json, false);
}

export function EventFromJSONTyped(json: any, ignoreDiscriminator: boolean): Event {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'source': !exists(json, 'source') ? undefined : json['source'],
        'args': !exists(json, 'args') ? undefined : json['args'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'recordedAt': !exists(json, 'recorded_at') ? undefined : (new Date(json['recorded_at'])),
        'accountId': !exists(json, 'account_id') ? undefined : json['account_id'],
    };
}

export function EventToJSON(value?: Event | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'source': value.source,
        'args': value.args,
        'url': value.url,
        'recorded_at': value.recordedAt === undefined ? undefined : (value.recordedAt.toISOString()),
        'account_id': value.accountId,
    };
}

