/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type FilterValue
 * The filter value.
 * @export
 */
export type FilterValue = Array<number> | Array<string> | number | string;

export function FilterValueFromJSON(json: any): FilterValue {
    return FilterValueFromJSONTyped(json, false);
}

export function FilterValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): FilterValue {
    if (json == null) {
        return json;
    }
    if (instanceOfArray<number>(json)) {
        return Array<number>FromJSONTyped(json, true);
    }
    if (instanceOfArray<string>(json)) {
        return Array<string>FromJSONTyped(json, true);
    }
    if (instanceOfnumber(json)) {
        return numberFromJSONTyped(json, true);
    }
    if (instanceOfstring(json)) {
        return stringFromJSONTyped(json, true);
    }

    return {} as any;
}

export function FilterValueToJSON(json: any): any {
    return FilterValueToJSONTyped(json, false);
}

export function FilterValueToJSONTyped(value?: FilterValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    if (instanceOfArray<number>(value)) {
        return Array<number>ToJSON(value as Array<number>);
    }
    if (instanceOfArray<string>(value)) {
        return Array<string>ToJSON(value as Array<string>);
    }
    if (instanceOfnumber(value)) {
        return numberToJSON(value as number);
    }
    if (instanceOfstring(value)) {
        return stringToJSON(value as string);
    }

    return {};
}

