/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenerateSitemap200Response
 */
export interface GenerateSitemap200Response {
    /**
     * The generated sitemap in XML format.
     * @type {string}
     * @memberof GenerateSitemap200Response
     */
    sitemap?: string;
}

/**
 * Check if a given object implements the GenerateSitemap200Response interface.
 */
export function instanceOfGenerateSitemap200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GenerateSitemap200ResponseFromJSON(json: any): GenerateSitemap200Response {
    return GenerateSitemap200ResponseFromJSONTyped(json, false);
}

export function GenerateSitemap200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateSitemap200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sitemap': !exists(json, 'sitemap') ? undefined : json['sitemap'],
    };
}

export function GenerateSitemap200ResponseToJSON(value?: GenerateSitemap200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sitemap': value.sitemap,
    };
}

