/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * InternalLink source configuration.
 * @export
 * @interface InternalLinkSource
 */
export interface InternalLinkSource {
    /**
     * Entity identifier.
     * @type {string}
     * @memberof InternalLinkSource
     */
    id?: string;
    /**
     * Entity name.
     * @type {string}
     * @memberof InternalLinkSource
     */
    name?: string;
    /**
     * Entity url.
     * @type {string}
     * @memberof InternalLinkSource
     */
    url: string;
}

/**
 * Check if a given object implements the InternalLinkSource interface.
 */
export function instanceOfInternalLinkSource(value: object): value is InternalLinkSource {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function InternalLinkSourceFromJSON(json: any): InternalLinkSource {
    return InternalLinkSourceFromJSONTyped(json, false);
}

export function InternalLinkSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalLinkSource {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'url': json['url'],
    };
}

export function InternalLinkSourceToJSON(json: any): InternalLinkSource {
    return InternalLinkSourceToJSONTyped(json, false);
}

export function InternalLinkSourceToJSONTyped(value?: InternalLinkSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'url': value['url'],
    };
}

