/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VectorSearchQueryRequest } from './VectorSearchQueryRequest';
import {
    VectorSearchQueryRequestFromJSON,
    VectorSearchQueryRequestFromJSONTyped,
    VectorSearchQueryRequestToJSON,
    VectorSearchQueryRequestToJSONTyped,
} from './VectorSearchQueryRequest';

/**
 * An Internal Link request item.
 * @export
 * @interface Item
 */
export interface Item {
    /**
     * The entity id, reused in the output template.
     * @type {string}
     * @memberof Item
     */
    id?: string;
    /**
     * 
     * @type {VectorSearchQueryRequest}
     * @memberof Item
     */
    query: VectorSearchQueryRequest;
    /**
     * The webpage name, reused in the output template.
     * @type {string}
     * @memberof Item
     */
    sourceName?: string;
}

/**
 * Check if a given object implements the Item interface.
 */
export function instanceOfItem(value: object): value is Item {
    if (!('query' in value) || value['query'] === undefined) return false;
    return true;
}

export function ItemFromJSON(json: any): Item {
    return ItemFromJSONTyped(json, false);
}

export function ItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): Item {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'query': VectorSearchQueryRequestFromJSON(json['query']),
        'sourceName': json['source_name'] == null ? undefined : json['source_name'],
    };
}

export function ItemToJSON(json: any): Item {
    return ItemToJSONTyped(json, false);
}

export function ItemToJSONTyped(value?: Item | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'query': VectorSearchQueryRequestToJSON(value['query']),
        'source_name': value['sourceName'],
    };
}

