/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KgEmbeddingRequest
 */
export interface KgEmbeddingRequest {
    /**
     * 
     * @type {string}
     * @memberof KgEmbeddingRequest
     */
    graphqlQuery?: string;
    /**
     * 
     * @type {Set<string>}
     * @memberof KgEmbeddingRequest
     */
    properties?: Set<string>;
}

/**
 * Check if a given object implements the KgEmbeddingRequest interface.
 */
export function instanceOfKgEmbeddingRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function KgEmbeddingRequestFromJSON(json: any): KgEmbeddingRequest {
    return KgEmbeddingRequestFromJSONTyped(json, false);
}

export function KgEmbeddingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): KgEmbeddingRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'graphqlQuery': !exists(json, 'graphql_query') ? undefined : json['graphql_query'],
        'properties': !exists(json, 'properties') ? undefined : json['properties'],
    };
}

export function KgEmbeddingRequestToJSON(value?: KgEmbeddingRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'graphql_query': value.graphqlQuery,
        'properties': value.properties === undefined ? undefined : Array.from(value.properties as Set<any>),
    };
}

