/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Entity1 } from './Entity1';
import {
    Entity1FromJSON,
    Entity1FromJSONTyped,
    Entity1ToJSON,
} from './Entity1';

/**
 * 
 * @export
 * @interface LongtailResponse
 */
export interface LongtailResponse {
    /**
     * The page summary.
     * @type {string}
     * @memberof LongtailResponse
     */
    summary?: string;
    /**
     * The list of entities matching the query.
     * @type {Array<Entity1>}
     * @memberof LongtailResponse
     */
    entities?: Array<Entity1>;
}

/**
 * Check if a given object implements the LongtailResponse interface.
 */
export function instanceOfLongtailResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LongtailResponseFromJSON(json: any): LongtailResponse {
    return LongtailResponseFromJSONTyped(json, false);
}

export function LongtailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LongtailResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'summary': !exists(json, 'summary') ? undefined : json['summary'],
        'entities': !exists(json, 'entities') ? undefined : ((json['entities'] as Array<any>).map(Entity1FromJSON)),
    };
}

export function LongtailResponseToJSON(value?: LongtailResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'summary': value.summary,
        'entities': value.entities === undefined ? undefined : ((value.entities as Array<any>).map(Entity1ToJSON)),
    };
}

