/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A Merchant Entry with the Google Merchant Id and the Website URL
 * @export
 * @interface MerchantEntry
 */
export interface MerchantEntry {
    /**
     * The Google Merchant id
     * @type {number}
     * @memberof MerchantEntry
     */
    googleMerchantId: number;
    /**
     * The Google Merchant Website URL
     * @type {string}
     * @memberof MerchantEntry
     */
    websiteUrl: string;
}

/**
 * Check if a given object implements the MerchantEntry interface.
 */
export function instanceOfMerchantEntry(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "googleMerchantId" in value;
    isInstance = isInstance && "websiteUrl" in value;

    return isInstance;
}

export function MerchantEntryFromJSON(json: any): MerchantEntry {
    return MerchantEntryFromJSONTyped(json, false);
}

export function MerchantEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): MerchantEntry {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'googleMerchantId': json['google_merchant_id'],
        'websiteUrl': json['website_url'],
    };
}

export function MerchantEntryToJSON(value?: MerchantEntry | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'google_merchant_id': value.googleMerchantId,
        'website_url': value.websiteUrl,
    };
}

