/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A language model.
 * @export
 * @interface Model
 */
export interface Model {
    /**
     * The unique id.
     * @type {number}
     * @memberof Model
     */
    readonly id?: number;
    /**
     * The language model name.
     * @type {string}
     * @memberof Model
     */
    name: string;
    /**
     * The system prompt for the model - chat models only.
     * @type {string}
     * @memberof Model
     */
    systemPrompt?: string;
    /**
     * The upper token margin for completions.
     * @type {number}
     * @memberof Model
     */
    tokenMargin?: number;
}

/**
 * Check if a given object implements the Model interface.
 */
export function instanceOfModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function ModelFromJSON(json: any): Model {
    return ModelFromJSONTyped(json, false);
}

export function ModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
        'systemPrompt': !exists(json, 'system_prompt') ? undefined : json['system_prompt'],
        'tokenMargin': !exists(json, 'token_margin') ? undefined : json['token_margin'],
    };
}

export function ModelToJSON(value?: Model | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'system_prompt': value.systemPrompt,
        'token_margin': value.tokenMargin,
    };
}

