/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MerchantView } from './MerchantView';
import {
    MerchantViewFromJSON,
    MerchantViewFromJSONTyped,
    MerchantViewToJSON,
} from './MerchantView';

/**
 * A page object with links to move to other pages and the list of objects.
 * @export
 * @interface PageMerchantView
 */
export interface PageMerchantView {
    /**
     * The link to the first page.
     * @type {string}
     * @memberof PageMerchantView
     */
    first: string | null;
    /**
     * An array of objects.
     * @type {Array<MerchantView>}
     * @memberof PageMerchantView
     */
    items: Array<MerchantView>;
    /**
     * The link to the last page.
     * @type {string}
     * @memberof PageMerchantView
     */
    last: string | null;
    /**
     * The link to the next page or `null` if there's no page.
     * @type {string}
     * @memberof PageMerchantView
     */
    next: string | null;
    /**
     * The link to the previous page or `null` if there's no page.
     * @type {string}
     * @memberof PageMerchantView
     */
    prev: string | null;
    /**
     * The link to the current page.
     * @type {string}
     * @memberof PageMerchantView
     */
    self: string | null;
}

/**
 * Check if a given object implements the PageMerchantView interface.
 */
export function instanceOfPageMerchantView(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "first" in value;
    isInstance = isInstance && "items" in value;
    isInstance = isInstance && "last" in value;
    isInstance = isInstance && "next" in value;
    isInstance = isInstance && "prev" in value;
    isInstance = isInstance && "self" in value;

    return isInstance;
}

export function PageMerchantViewFromJSON(json: any): PageMerchantView {
    return PageMerchantViewFromJSONTyped(json, false);
}

export function PageMerchantViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageMerchantView {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'first': json['first'],
        'items': ((json['items'] as Array<any>).map(MerchantViewFromJSON)),
        'last': json['last'],
        'next': json['next'],
        'prev': json['prev'],
        'self': json['self'],
    };
}

export function PageMerchantViewToJSON(value?: PageMerchantView | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'first': value.first,
        'items': ((value.items as Array<any>).map(MerchantViewToJSON)),
        'last': value.last,
        'next': value.next,
        'prev': value.prev,
        'self': value.self,
    };
}

