/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Platform Limit request
 * @export
 * @interface PlatformLimitRequest
 */
export interface PlatformLimitRequest {
    /**
     * 
     * @type {string}
     * @memberof PlatformLimitRequest
     */
    appliesTo: string;
    /**
     * 
     * @type {string}
     * @memberof PlatformLimitRequest
     */
    basedOn: PlatformLimitRequestBasedOnEnum;
    /**
     * 
     * @type {string}
     * @memberof PlatformLimitRequest
     */
    basedOnValue: string;
    /**
     * 
     * @type {string}
     * @memberof PlatformLimitRequest
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof PlatformLimitRequest
     */
    limits: number;
    /**
     * 
     * @type {string}
     * @memberof PlatformLimitRequest
     */
    scope: PlatformLimitRequestScopeEnum;
}


/**
 * @export
 */
export const PlatformLimitRequestBasedOnEnum = {
    Sku: 'SKU'
} as const;
export type PlatformLimitRequestBasedOnEnum = typeof PlatformLimitRequestBasedOnEnum[keyof typeof PlatformLimitRequestBasedOnEnum];

/**
 * @export
 */
export const PlatformLimitRequestScopeEnum = {
    Account: 'ACCOUNT',
    Subscription: 'SUBSCRIPTION'
} as const;
export type PlatformLimitRequestScopeEnum = typeof PlatformLimitRequestScopeEnum[keyof typeof PlatformLimitRequestScopeEnum];


/**
 * Check if a given object implements the PlatformLimitRequest interface.
 */
export function instanceOfPlatformLimitRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "appliesTo" in value;
    isInstance = isInstance && "basedOn" in value;
    isInstance = isInstance && "basedOnValue" in value;
    isInstance = isInstance && "limits" in value;
    isInstance = isInstance && "scope" in value;

    return isInstance;
}

export function PlatformLimitRequestFromJSON(json: any): PlatformLimitRequest {
    return PlatformLimitRequestFromJSONTyped(json, false);
}

export function PlatformLimitRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlatformLimitRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'appliesTo': json['applies_to'],
        'basedOn': json['based_on'],
        'basedOnValue': json['based_on_value'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'limits': json['limits'],
        'scope': json['scope'],
    };
}

export function PlatformLimitRequestToJSON(value?: PlatformLimitRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'applies_to': value.appliesTo,
        'based_on': value.basedOn,
        'based_on_value': value.basedOnValue,
        'description': value.description,
        'limits': value.limits,
        'scope': value.scope,
    };
}

