/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An array of objects.
 * @export
 * @interface Preset
 */
export interface Preset {
    /**
     * The predefined graphql query.
     * @type {string}
     * @memberof Preset
     */
    body: string;
    /**
     * 
     * @type {number}
     * @memberof Preset
     */
    id?: number;
    /**
     * The label of the preset.
     * @type {string}
     * @memberof Preset
     */
    label: string;
}

/**
 * Check if a given object implements the Preset interface.
 */
export function instanceOfPreset(value: object): value is Preset {
    if (!('body' in value) || value['body'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    return true;
}

export function PresetFromJSON(json: any): Preset {
    return PresetFromJSONTyped(json, false);
}

export function PresetFromJSONTyped(json: any, ignoreDiscriminator: boolean): Preset {
    if (json == null) {
        return json;
    }
    return {
        
        'body': json['body'],
        'id': json['id'] == null ? undefined : json['id'],
        'label': json['label'],
    };
}

export function PresetToJSON(json: any): Preset {
    return PresetToJSONTyped(json, false);
}

export function PresetToJSONTyped(value?: Preset | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'body': value['body'],
        'id': value['id'],
        'label': value['label'],
    };
}

