/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The project type, if applicable.
 * @export
 */
export const ProjectType = {
    SmartContent: 'SMART_CONTENT',
    ContentGeneration: 'CONTENT_GENERATION'
} as const;
export type ProjectType = typeof ProjectType[keyof typeof ProjectType];


export function ProjectTypeFromJSON(json: any): ProjectType {
    return ProjectTypeFromJSONTyped(json, false);
}

export function ProjectTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectType {
    return json as ProjectType;
}

export function ProjectTypeToJSON(value?: ProjectType | null): any {
    return value as any;
}

