/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebpageProperties } from './WebpageProperties';
import {
    WebpagePropertiesFromJSON,
    WebpagePropertiesFromJSONTyped,
    WebpagePropertiesToJSON,
    WebpagePropertiesToJSONTyped,
} from './WebpageProperties';

/**
 * 
 * @export
 * @interface QuestionAndAnswerRequest
 */
export interface QuestionAndAnswerRequest {
    /**
     * 
     * @type {number}
     * @memberof QuestionAndAnswerRequest
     */
    smartContentId?: number;
    /**
     * 
     * @type {WebpageProperties}
     * @memberof QuestionAndAnswerRequest
     */
    webpageProperties?: WebpageProperties;
}

/**
 * Check if a given object implements the QuestionAndAnswerRequest interface.
 */
export function instanceOfQuestionAndAnswerRequest(value: object): value is QuestionAndAnswerRequest {
    return true;
}

export function QuestionAndAnswerRequestFromJSON(json: any): QuestionAndAnswerRequest {
    return QuestionAndAnswerRequestFromJSONTyped(json, false);
}

export function QuestionAndAnswerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuestionAndAnswerRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'smartContentId': json['smartContentId'] == null ? undefined : json['smartContentId'],
        'webpageProperties': json['webpageProperties'] == null ? undefined : WebpagePropertiesFromJSON(json['webpageProperties']),
    };
}

export function QuestionAndAnswerRequestToJSON(json: any): QuestionAndAnswerRequest {
    return QuestionAndAnswerRequestToJSONTyped(json, false);
}

export function QuestionAndAnswerRequestToJSONTyped(value?: QuestionAndAnswerRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'smartContentId': value['smartContentId'],
        'webpageProperties': WebpagePropertiesToJSON(value['webpageProperties']),
    };
}

