/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A Smart Content project.
 * @export
 * @interface SmartContent
 */
export interface SmartContent {
    /**
     * The account id.
     * @type {number}
     * @memberof SmartContent
     */
    readonly accountId: number;
    /**
     * The create date-time.
     * @type {Date}
     * @memberof SmartContent
     */
    readonly createdAt?: Date;
    /**
     * The unique id.
     * @type {number}
     * @memberof SmartContent
     */
    readonly id?: number;
    /**
     * The model id.
     * @type {number}
     * @memberof SmartContent
     */
    modelId?: number;
}

/**
 * Check if a given object implements the SmartContent interface.
 */
export function instanceOfSmartContent(value: object): value is SmartContent {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    return true;
}

export function SmartContentFromJSON(json: any): SmartContent {
    return SmartContentFromJSONTyped(json, false);
}

export function SmartContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): SmartContent {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['account_id'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'id': json['id'] == null ? undefined : json['id'],
        'modelId': json['model_id'] == null ? undefined : json['model_id'],
    };
}

export function SmartContentToJSON(json: any): SmartContent {
    return SmartContentToJSONTyped(json, false);
}

export function SmartContentToJSONTyped(value?: Omit<SmartContent, 'account_id'|'created_at'|'id'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'model_id': value['modelId'],
    };
}

