/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubmitFactCheckRequest
 */
export interface SubmitFactCheckRequest {
    /**
     * 
     * @type {string}
     * @memberof SubmitFactCheckRequest
     */
    query?: string;
}

/**
 * Check if a given object implements the SubmitFactCheckRequest interface.
 */
export function instanceOfSubmitFactCheckRequest(value: object): value is SubmitFactCheckRequest {
    return true;
}

export function SubmitFactCheckRequestFromJSON(json: any): SubmitFactCheckRequest {
    return SubmitFactCheckRequestFromJSONTyped(json, false);
}

export function SubmitFactCheckRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmitFactCheckRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'query': json['query'] == null ? undefined : json['query'],
    };
}

export function SubmitFactCheckRequestToJSON(json: any): SubmitFactCheckRequest {
    return SubmitFactCheckRequestToJSONTyped(json, false);
}

export function SubmitFactCheckRequestToJSONTyped(value?: SubmitFactCheckRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'query': value['query'],
    };
}

