/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A request to update the properties of multiple records.
 * @export
 * @interface UpdateRecordsRequest
 */
export interface UpdateRecordsRequest {
    /**
     * The validation time of the record.
     * @type {Date}
     * @memberof UpdateRecordsRequest
     */
    validatedAt?: Date;
}

/**
 * Check if a given object implements the UpdateRecordsRequest interface.
 */
export function instanceOfUpdateRecordsRequest(value: object): value is UpdateRecordsRequest {
    return true;
}

export function UpdateRecordsRequestFromJSON(json: any): UpdateRecordsRequest {
    return UpdateRecordsRequestFromJSONTyped(json, false);
}

export function UpdateRecordsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateRecordsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'validatedAt': json['validated_at'] == null ? undefined : (new Date(json['validated_at'])),
    };
}

export function UpdateRecordsRequestToJSON(json: any): UpdateRecordsRequest {
    return UpdateRecordsRequestToJSONTyped(json, false);
}

export function UpdateRecordsRequestToJSONTyped(value?: UpdateRecordsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'validated_at': value['validatedAt'] == null ? undefined : ((value['validatedAt']).toISOString()),
    };
}

