/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The operator for what condition.
 * @export
 */
export const WhatOperator = {
    Contains: 'CONTAINS',
    DoesntContain: 'DOESNT_CONTAIN',
    EndsWith: 'ENDS_WITH',
    Regex: 'REGEX',
    RegexDoesntMatch: 'REGEX_DOESNT_MATCH'
} as const;
export type WhatOperator = typeof WhatOperator[keyof typeof WhatOperator];


export function instanceOfWhatOperator(value: any): boolean {
    for (const key in WhatOperator) {
        if (Object.prototype.hasOwnProperty.call(WhatOperator, key)) {
            if (WhatOperator[key as keyof typeof WhatOperator] === value) {
                return true;
            }
        }
    }
    return false;
}

export function WhatOperatorFromJSON(json: any): WhatOperator {
    return WhatOperatorFromJSONTyped(json, false);
}

export function WhatOperatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): WhatOperator {
    return json as WhatOperator;
}

export function WhatOperatorToJSON(value?: WhatOperator | null): any {
    return value as any;
}

export function WhatOperatorToJSONTyped(value: any, ignoreDiscriminator: boolean): WhatOperator {
    return value as WhatOperator;
}

