/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The operator for when condition.
 * @export
 */
export const WhenOperator = {
    Always: 'ALWAYS',
    Equals: 'EQUALS',
    NotEquals: 'NOT_EQUALS'
} as const;
export type WhenOperator = typeof WhenOperator[keyof typeof WhenOperator];


export function instanceOfWhenOperator(value: any): boolean {
    for (const key in WhenOperator) {
        if (Object.prototype.hasOwnProperty.call(WhenOperator, key)) {
            if (WhenOperator[key as keyof typeof WhenOperator] === value) {
                return true;
            }
        }
    }
    return false;
}

export function WhenOperatorFromJSON(json: any): WhenOperator {
    return WhenOperatorFromJSONTyped(json, false);
}

export function WhenOperatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): WhenOperator {
    return json as WhenOperator;
}

export function WhenOperatorToJSON(value?: WhenOperator | null): any {
    return value as any;
}

export function WhenOperatorToJSONTyped(value: any, ignoreDiscriminator: boolean): WhenOperator {
    return value as WhenOperator;
}

