/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WordRequest
 */
export interface WordRequest {
    /**
     * The bias.
     * @type {number}
     * @memberof WordRequest
     */
    bias: number;
    /**
     * The actual word.
     * @type {string}
     * @memberof WordRequest
     */
    word: string;
}

/**
 * Check if a given object implements the WordRequest interface.
 */
export function instanceOfWordRequest(value: object): value is WordRequest {
    if (!('bias' in value) || value['bias'] === undefined) return false;
    if (!('word' in value) || value['word'] === undefined) return false;
    return true;
}

export function WordRequestFromJSON(json: any): WordRequest {
    return WordRequestFromJSONTyped(json, false);
}

export function WordRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WordRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'bias': json['bias'],
        'word': json['word'],
    };
}

export function WordRequestToJSON(json: any): WordRequest {
    return WordRequestToJSONTyped(json, false);
}

export function WordRequestToJSONTyped(value?: WordRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bias': value['bias'],
        'word': value['word'],
    };
}

