/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The request of the `buildAuthorizeUri` endpoint.
 * @export
 * @interface BuildAuthorizeUriRequest
 */
export interface BuildAuthorizeUriRequest {
    /**
     * The Redirect URI to where redirect the Client after successful authentication.
     * @type {string}
     * @memberof BuildAuthorizeUriRequest
     */
    redirectUri: string;
}

/**
 * Check if a given object implements the BuildAuthorizeUriRequest interface.
 */
export function instanceOfBuildAuthorizeUriRequest(value: object): value is BuildAuthorizeUriRequest {
    if (!('redirectUri' in value) || value['redirectUri'] === undefined) return false;
    return true;
}

export function BuildAuthorizeUriRequestFromJSON(json: any): BuildAuthorizeUriRequest {
    return BuildAuthorizeUriRequestFromJSONTyped(json, false);
}

export function BuildAuthorizeUriRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BuildAuthorizeUriRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'redirectUri': json['redirect_uri'],
    };
}

export function BuildAuthorizeUriRequestToJSON(json: any): BuildAuthorizeUriRequest {
    return BuildAuthorizeUriRequestToJSONTyped(json, false);
}

export function BuildAuthorizeUriRequestToJSONTyped(value?: BuildAuthorizeUriRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'redirect_uri': value['redirectUri'],
    };
}

