/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Diagnostic Plugin Data Request
 * @export
 * @interface DiagnosticPluginRequest
 */
export interface DiagnosticPluginRequest {
    /**
     * Whether the plugin is active.
     * @type {boolean}
     * @memberof DiagnosticPluginRequest
     */
    active?: boolean;
    /**
     * The plugin name.
     * @type {string}
     * @memberof DiagnosticPluginRequest
     */
    name?: string;
    /**
     * The plugin version.
     * @type {string}
     * @memberof DiagnosticPluginRequest
     */
    version?: string;
}

/**
 * Check if a given object implements the DiagnosticPluginRequest interface.
 */
export function instanceOfDiagnosticPluginRequest(value: object): value is DiagnosticPluginRequest {
    return true;
}

export function DiagnosticPluginRequestFromJSON(json: any): DiagnosticPluginRequest {
    return DiagnosticPluginRequestFromJSONTyped(json, false);
}

export function DiagnosticPluginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiagnosticPluginRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'active': json['active'] == null ? undefined : json['active'],
        'name': json['name'] == null ? undefined : json['name'],
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function DiagnosticPluginRequestToJSON(json: any): DiagnosticPluginRequest {
    return DiagnosticPluginRequestToJSONTyped(json, false);
}

export function DiagnosticPluginRequestToJSONTyped(value?: DiagnosticPluginRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'active': value['active'],
        'name': value['name'],
        'version': value['version'],
    };
}

