/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DuplicateAuthorizationRequest
 */
export interface DuplicateAuthorizationRequest {
    /**
     * 
     * @type {string}
     * @memberof DuplicateAuthorizationRequest
     */
    fromAccountKey: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof DuplicateAuthorizationRequest
     */
    toAccountKeys: Array<string>;
}

/**
 * Check if a given object implements the DuplicateAuthorizationRequest interface.
 */
export function instanceOfDuplicateAuthorizationRequest(value: object): value is DuplicateAuthorizationRequest {
    if (!('fromAccountKey' in value) || value['fromAccountKey'] === undefined) return false;
    if (!('toAccountKeys' in value) || value['toAccountKeys'] === undefined) return false;
    return true;
}

export function DuplicateAuthorizationRequestFromJSON(json: any): DuplicateAuthorizationRequest {
    return DuplicateAuthorizationRequestFromJSONTyped(json, false);
}

export function DuplicateAuthorizationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DuplicateAuthorizationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'fromAccountKey': json['from_account_key'],
        'toAccountKeys': json['to_account_keys'],
    };
}

export function DuplicateAuthorizationRequestToJSON(json: any): DuplicateAuthorizationRequest {
    return DuplicateAuthorizationRequestToJSONTyped(json, false);
}

export function DuplicateAuthorizationRequestToJSONTyped(value?: DuplicateAuthorizationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'from_account_key': value['fromAccountKey'],
        'to_account_keys': value['toAccountKeys'],
    };
}

