/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A request to generate the embeddings.
 * @export
 * @interface EmbeddingRequest
 */
export interface EmbeddingRequest {
    /**
     * The model used to generate the embeddings.
     * @type {string}
     * @memberof EmbeddingRequest
     */
    model?: string;
    /**
     * The list of properties to use to generate the embeddings.
     * @type {Set<string>}
     * @memberof EmbeddingRequest
     */
    properties?: Set<string>;
}

/**
 * Check if a given object implements the EmbeddingRequest interface.
 */
export function instanceOfEmbeddingRequest(value: object): value is EmbeddingRequest {
    return true;
}

export function EmbeddingRequestFromJSON(json: any): EmbeddingRequest {
    return EmbeddingRequestFromJSONTyped(json, false);
}

export function EmbeddingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmbeddingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'model': json['model'] == null ? undefined : json['model'],
        'properties': json['properties'] == null ? undefined : new Set(json['properties']),
    };
}

export function EmbeddingRequestToJSON(json: any): EmbeddingRequest {
    return EmbeddingRequestToJSONTyped(json, false);
}

export function EmbeddingRequestToJSONTyped(value?: EmbeddingRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'model': value['model'],
        'properties': value['properties'] == null ? undefined : Array.from(value['properties'] as Set<any>),
    };
}

