/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContentGeneration } from './ContentGeneration';
import {
    ContentGenerationFromJSON,
    ContentGenerationFromJSONTyped,
    ContentGenerationToJSON,
    ContentGenerationToJSONTyped,
} from './ContentGeneration';

/**
 * A page object with links to move to other pages and the list of objects.
 * @export
 * @interface PageContentGeneration
 */
export interface PageContentGeneration {
    /**
     * The link to the first page.
     * @type {string}
     * @memberof PageContentGeneration
     */
    first: string | null;
    /**
     * An array of objects.
     * @type {Array<ContentGeneration>}
     * @memberof PageContentGeneration
     */
    items: Array<ContentGeneration>;
    /**
     * The link to the last page.
     * @type {string}
     * @memberof PageContentGeneration
     */
    last: string | null;
    /**
     * The link to the next page or `null` if there's no page.
     * @type {string}
     * @memberof PageContentGeneration
     */
    next: string | null;
    /**
     * The link to the previous page or `null` if there's no page.
     * @type {string}
     * @memberof PageContentGeneration
     */
    prev: string | null;
    /**
     * The link to the current page.
     * @type {string}
     * @memberof PageContentGeneration
     */
    self: string | null;
}

/**
 * Check if a given object implements the PageContentGeneration interface.
 */
export function instanceOfPageContentGeneration(value: object): value is PageContentGeneration {
    if (!('first' in value) || value['first'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('last' in value) || value['last'] === undefined) return false;
    if (!('next' in value) || value['next'] === undefined) return false;
    if (!('prev' in value) || value['prev'] === undefined) return false;
    if (!('self' in value) || value['self'] === undefined) return false;
    return true;
}

export function PageContentGenerationFromJSON(json: any): PageContentGeneration {
    return PageContentGenerationFromJSONTyped(json, false);
}

export function PageContentGenerationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageContentGeneration {
    if (json == null) {
        return json;
    }
    return {
        
        'first': json['first'],
        'items': ((json['items'] as Array<any>).map(ContentGenerationFromJSON)),
        'last': json['last'],
        'next': json['next'],
        'prev': json['prev'],
        'self': json['self'],
    };
}

export function PageContentGenerationToJSON(json: any): PageContentGeneration {
    return PageContentGenerationToJSONTyped(json, false);
}

export function PageContentGenerationToJSONTyped(value?: PageContentGeneration | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first': value['first'],
        'items': ((value['items'] as Array<any>).map(ContentGenerationToJSON)),
        'last': value['last'],
        'next': value['next'],
        'prev': value['prev'],
        'self': value['self'],
    };
}

