/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Rule } from './Rule';
import {
    RuleFromJSON,
    RuleFromJSONTyped,
    RuleToJSON,
    RuleToJSONTyped,
} from './Rule';

/**
 * A page object with links to move to other pages and the list of objects.
 * @export
 * @interface PageRule
 */
export interface PageRule {
    /**
     * The link to the first page.
     * @type {string}
     * @memberof PageRule
     */
    first: string | null;
    /**
     * An array of objects.
     * @type {Array<Rule>}
     * @memberof PageRule
     */
    items: Array<Rule>;
    /**
     * The link to the last page.
     * @type {string}
     * @memberof PageRule
     */
    last: string | null;
    /**
     * The link to the next page or `null` if there's no page.
     * @type {string}
     * @memberof PageRule
     */
    next: string | null;
    /**
     * The link to the previous page or `null` if there's no page.
     * @type {string}
     * @memberof PageRule
     */
    prev: string | null;
    /**
     * The link to the current page.
     * @type {string}
     * @memberof PageRule
     */
    self: string | null;
}

/**
 * Check if a given object implements the PageRule interface.
 */
export function instanceOfPageRule(value: object): value is PageRule {
    if (!('first' in value) || value['first'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('last' in value) || value['last'] === undefined) return false;
    if (!('next' in value) || value['next'] === undefined) return false;
    if (!('prev' in value) || value['prev'] === undefined) return false;
    if (!('self' in value) || value['self'] === undefined) return false;
    return true;
}

export function PageRuleFromJSON(json: any): PageRule {
    return PageRuleFromJSONTyped(json, false);
}

export function PageRuleFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageRule {
    if (json == null) {
        return json;
    }
    return {
        
        'first': json['first'],
        'items': ((json['items'] as Array<any>).map(RuleFromJSON)),
        'last': json['last'],
        'next': json['next'],
        'prev': json['prev'],
        'self': json['self'],
    };
}

export function PageRuleToJSON(json: any): PageRule {
    return PageRuleToJSONTyped(json, false);
}

export function PageRuleToJSONTyped(value?: PageRule | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first': value['first'],
        'items': ((value['items'] as Array<any>).map(RuleToJSON)),
        'last': value['last'],
        'next': value['next'],
        'prev': value['prev'],
        'self': value['self'],
    };
}

