/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Record } from './Record';
import {
    RecordFromJSON,
    RecordFromJSONTyped,
    RecordToJSON,
    RecordToJSONTyped,
} from './Record';

/**
 * A page object with links to move to other pages and the list of objects.
 * @export
 * @interface PageRecord
 */
export interface PageRecord {
    /**
     * The link to the first page.
     * @type {string}
     * @memberof PageRecord
     */
    first: string | null;
    /**
     * An array of objects.
     * @type {Array<Record>}
     * @memberof PageRecord
     */
    items: Array<Record>;
    /**
     * The link to the last page.
     * @type {string}
     * @memberof PageRecord
     */
    last: string | null;
    /**
     * The link to the next page or `null` if there's no page.
     * @type {string}
     * @memberof PageRecord
     */
    next: string | null;
    /**
     * The link to the previous page or `null` if there's no page.
     * @type {string}
     * @memberof PageRecord
     */
    prev: string | null;
    /**
     * The link to the current page.
     * @type {string}
     * @memberof PageRecord
     */
    self: string | null;
}

/**
 * Check if a given object implements the PageRecord interface.
 */
export function instanceOfPageRecord(value: object): value is PageRecord {
    if (!('first' in value) || value['first'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('last' in value) || value['last'] === undefined) return false;
    if (!('next' in value) || value['next'] === undefined) return false;
    if (!('prev' in value) || value['prev'] === undefined) return false;
    if (!('self' in value) || value['self'] === undefined) return false;
    return true;
}

export function PageRecordFromJSON(json: any): PageRecord {
    return PageRecordFromJSONTyped(json, false);
}

export function PageRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'first': json['first'],
        'items': ((json['items'] as Array<any>).map(RecordFromJSON)),
        'last': json['last'],
        'next': json['next'],
        'prev': json['prev'],
        'self': json['self'],
    };
}

export function PageRecordToJSON(json: any): PageRecord {
    return PageRecordToJSONTyped(json, false);
}

export function PageRecordToJSONTyped(value?: PageRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first': value['first'],
        'items': ((value['items'] as Array<any>).map(RecordToJSON)),
        'last': value['last'],
        'next': value['next'],
        'prev': value['prev'],
        'self': value['self'],
    };
}

