/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Request2
 */
export interface Request2 {
    /**
     * 
     * @type {string}
     * @memberof Request2
     */
    redeemCode?: string;
}

/**
 * Check if a given object implements the Request2 interface.
 */
export function instanceOfRequest2(value: object): value is Request2 {
    return true;
}

export function Request2FromJSON(json: any): Request2 {
    return Request2FromJSONTyped(json, false);
}

export function Request2FromJSONTyped(json: any, ignoreDiscriminator: boolean): Request2 {
    if (json == null) {
        return json;
    }
    return {
        
        'redeemCode': json['redeem_code'] == null ? undefined : json['redeem_code'],
    };
}

export function Request2ToJSON(json: any): Request2 {
    return Request2ToJSONTyped(json, false);
}

export function Request2ToJSONTyped(value?: Request2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'redeem_code': value['redeemCode'],
    };
}

