/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateAccountRequest
 */
export interface UpdateAccountRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateAccountRequest
     */
    country?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAccountRequest
     */
    language?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAccountRequest
     */
    url?: string;
}

/**
 * Check if a given object implements the UpdateAccountRequest interface.
 */
export function instanceOfUpdateAccountRequest(value: object): value is UpdateAccountRequest {
    return true;
}

export function UpdateAccountRequestFromJSON(json: any): UpdateAccountRequest {
    return UpdateAccountRequestFromJSONTyped(json, false);
}

export function UpdateAccountRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAccountRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'country': json['country'] == null ? undefined : json['country'],
        'language': json['language'] == null ? undefined : json['language'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function UpdateAccountRequestToJSON(json: any): UpdateAccountRequest {
    return UpdateAccountRequestToJSONTyped(json, false);
}

export function UpdateAccountRequestToJSONTyped(value?: UpdateAccountRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'country': value['country'],
        'language': value['language'],
        'url': value['url'],
    };
}

