/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateQuestionAndAnswerRequest
 */
export interface UpdateQuestionAndAnswerRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateQuestionAndAnswerRequest
     */
    answer?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateQuestionAndAnswerRequest
     */
    question?: string;
}

/**
 * Check if a given object implements the UpdateQuestionAndAnswerRequest interface.
 */
export function instanceOfUpdateQuestionAndAnswerRequest(value: object): value is UpdateQuestionAndAnswerRequest {
    return true;
}

export function UpdateQuestionAndAnswerRequestFromJSON(json: any): UpdateQuestionAndAnswerRequest {
    return UpdateQuestionAndAnswerRequestFromJSONTyped(json, false);
}

export function UpdateQuestionAndAnswerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateQuestionAndAnswerRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'answer': json['answer'] == null ? undefined : json['answer'],
        'question': json['question'] == null ? undefined : json['question'],
    };
}

export function UpdateQuestionAndAnswerRequestToJSON(json: any): UpdateQuestionAndAnswerRequest {
    return UpdateQuestionAndAnswerRequestToJSONTyped(json, false);
}

export function UpdateQuestionAndAnswerRequestToJSONTyped(value?: UpdateQuestionAndAnswerRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'answer': value['answer'],
        'question': value['question'],
    };
}

