/* tslint:disable */
/* eslint-disable */
/**
 * Embeddings API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Account,
  DiagnosticPluginRequest,
} from '../models/index';
import {
    AccountFromJSON,
    AccountToJSON,
    DiagnosticPluginRequestFromJSON,
    DiagnosticPluginRequestToJSON,
} from '../models/index';

export interface UpdateDiagnosticPluginCollectionRequest {
    account: Account;
    diagnosticPluginRequest: Array<DiagnosticPluginRequest>;
}

/**
 * 
 */
export class PluginDiagnosticsApi extends runtime.BaseAPI {

    /**
     * Replace the list of the plugins for the current account with the one provided by the client
     * Update
     */
    async updateDiagnosticPluginCollectionRaw(requestParameters: UpdateDiagnosticPluginCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['account'] == null) {
            throw new runtime.RequiredError(
                'account',
                'Required parameter "account" was null or undefined when calling updateDiagnosticPluginCollection().'
            );
        }

        if (requestParameters['diagnosticPluginRequest'] == null) {
            throw new runtime.RequiredError(
                'diagnosticPluginRequest',
                'Required parameter "diagnosticPluginRequest" was null or undefined when calling updateDiagnosticPluginCollection().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['account'] != null) {
            queryParameters['account'] = requestParameters['account'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }

        const response = await this.request({
            path: `/accounts/me/plugin/diagnostics/plugins-collection`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['diagnosticPluginRequest']!.map(DiagnosticPluginRequestToJSON),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Replace the list of the plugins for the current account with the one provided by the client
     * Update
     */
    async updateDiagnosticPluginCollection(requestParameters: UpdateDiagnosticPluginCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateDiagnosticPluginCollectionRaw(requestParameters, initOverrides);
    }

}
