name: Publish TypeScript Client to npm

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    name: Generate TypeScript Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 4: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.7.17"

      # Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.pinned.txt
          pip install build

      # Run the Python script to generate json for openApi-merge
      - name: Merge OpenAPI files
        run: python3 ./.bin/json_merge_generator.py

      # Merge the YAML files
      - name: Merge the yaml files
        run: npx openapi-merge-cli --config ./openapi-merge.json

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install OpenAPI Generator CLI
        run: npm install -g @openapitools/openapi-generator-cli

      - name: Generate TypeScript Client
        run: |
          openapi-generator-cli generate \
            -i ./wordliftApiSpec.yaml \
            -g typescript-fetch \
            -o ./generated-client \
            --additional-properties=packageName=wordlift_client

#  publish:
#    name: Publish to npm
#    runs-on: ubuntu-latest
#    needs: generate
#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v4
#
#      - name: Set Up Node.js
#        uses: actions/setup-node@v3
#        with:
#          node-version: '20'
#          registry-url: 'https://registry.npmjs.org'
#
#      - name: Install Dependencies
#        run: npm install
#
#      - name: Build Package
#        run: npm run build
#
#      - name: Publish Package
#        run: npm publish
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
